HOSTS:
  qamodule-osx-1012-agent:
    roles:
      - agent
      - default
    platform: osx-10.12-x86_64
    hypervisor: vagrant
    box: jhcook/macos-sierra
    vagrant_memsize: 4096
CONFIG:
  nfs_server: none
  consoleport: 443
  datastore: instance0
  folder: Delivery/Quality Assurance/Enterprise/Dynamic
